/**
 * Bike rides API
 * Bike rides API for managing bike rides
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Model { 
    id?: number;
    makeId?: number;
    categoryId?: number;
    name: string;
    shortName?: string;
    yearFrom?: number;
    yearTo?: number;
    dryWeight?: number;
    wetWeight?: number;
    seatHeight?: number;
    engineCapacity?: number;
    enginePower?: number;
    engineTorque?: number;
    topSpeed?: number;
    fuelCapacity?: number;
    fuelConsumption?: number;
    wheelbase?: number;
    overallLength?: number;
    homologatedForRoadUse?: boolean;
}

