spring:
  datasource:
    url: jdbc:h2:mem:testdb;mode=mssqlserver
    driver-class-name: org.h2.Driver
    hikari:
      username: sa
      password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
